### ISSUE TITLE
When the app starts, accessing "/browse" does not work

### ISSUE THREAD

**Issue by javac9** [crnk-project/crnk-example#2]
I am able to start the app, however, accessing http://127.0.0.1:8080/browse does not work, the error is shown:

`Whitelabel Error Page`
`This application has no explicit mapping for /error, so you are seeing this as a fallback.`

**Comment by remmeier** [comment]
see https://github.com/crnk-project/crnk-framework/pull/189

**Comment by remmeier** [comment]
I will an upgrade to crnk 2.6 soon (will be released this week). The issue should then disappear. The url should rather than also be /browser/ and not /browser

**Comment by remmeier** [comment]
has been upgrade, url available as /browse/

**Comment by remmeier** [comment]
(now also listed in /api/)
